name: Hedera Smart Contract CI

on: 
  workflow_dispatch:
    inputs:
      images:
        description: 'Image tags to run tests on'
        required: true
        default: 'latest'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
